### ISSUE TITLE
installation trouble

### ISSUE THREAD

**Issue by genkiboy** [philchalmers/mirt#19]
I'm getting errors trying to install the latest version.  Here's my R code and output (with some formatting to enhance readability):

> '> library('devtools')
> '> install_github('mirt', 'philchalmers', quick = TRUE)
> Installing github repo(s) mirt/master from philchalmers
> Installing mirt.zip from https://github.com/philchalmers/mirt/archive/master.zip
> Installing mirt
> "C:/PROGRA~1/R/R-215~1.3/bin/x64/R" --vanilla CMD build  \
>   "C:\Users\USERNAME\AppData\Local\Temp\RtmpI1eE0M\mirt-master" --no-manual  \
>   --no-resave-data --no-vignettes 
> - checking for file 'C:\Users\USERNAME\AppData\Local\Temp\RtmpI1eE0M\mirt-master/DESCRIPTION' ... OK
> - preparing 'mirt':
> - checking DESCRIPTION meta-information ... OK
> - cleaning src
> - checking for LF line-endings in source and make files
> - checking for empty or unneeded directories
> - looking to see if a 'data/datalist' file should be added
> - building 'mirt_0.6.1.tar.gz'
> 
> "C:/PROGRA~1/R/R-215~1.3/bin/x64/R" --vanilla CMD INSTALL  \
>   "C:\Users\USERNAME\AppData\Local\Temp\RtmpI1eE0M/mirt_0.6.1.tar.gz"  \
>   --library="C:/Program Files/R/R-2.15.3/library" --with-keep.source --no-docs  \
>   --no-multiarch --no-demo 
> - installing _source_ package 'mirt' ...
> - - libs
> 
> > g++ -m64 -I"C:/PROGRA~1/R/R-215~1.3/include" -DNDEBUG    -I"C:/Program Files/R/R->2.15.3/library/Rcpp/include" -I"d:/RCompile/CRANpkg/extralibs64/local/include"     -O2 -Wall  -mtune=core2 -c Estep.cpp -o Estep.o
> > g++ -m64 -I"C:/PROGRA~1/R/R-215~1.3/include" -DNDEBUG    -I"C:/Program Files/R/R-2.15.3/library/Rcpp/include" -I"d:/RCompile/CRANpkg/extralibs64/local/include"     -O2 -Wall  -mtune=core2 -c Misc.cpp -o Misc.o
> > gcc -m64 -I"C:/PROGRA~1/R/R-215~1.3/include" -DNDEBUG    -I"C:/Program Files/R/R-2.15.3/library/Rcpp/include" -I"d:/RCompile/CRANpkg/extralibs64/local/include"     -O2 -Wall  -std=gnu99 -mtune=core2 -c dgroup.c -o dgroup.o
> > g++ -m64 -I"C:/PROGRA~1/R/R-215~1.3/include" -DNDEBUG    -I"C:/Program Files/R/R-2.15.3/library/Rcpp/include" -I"d:/RCompile/CRANpkg/extralibs64/local/include"     -O2 -Wall  -mtune=core2 -c dpars.cpp -o dpars.o
> > g++ -m64 -I"C:/PROGRA~1/R/R-215~1.3/include" -DNDEBUG    -I"C:/Program Files/R/R-2.15.3/library/Rcpp/include" -I"d:/RCompile/CRANpkg/extralibs64/local/include"     -O2 -Wall  -mtune=core2 -c traceLinePts.cpp -o traceLinePts.o
> > g++ -m64 -shared -s -static-libgcc -o mirt.dll tmp.def Estep.o Misc.o dgroup.o dpars.o traceLinePts.o C:/Program Files/R/R-2.15.3/library/Rcpp/lib/x64/libRcpp.a -Ld:/RCompile/CRANpkg/extralibs64/local/lib/x64 -Ld:/RCompile/CRANpkg/extralibs64/local/lib -LC:/PROGRA~1/R/R-215~1.3/bin/x64 -lR
> > g++.exe: error: C:/Program: No such file or directory
> > g++.exe: error: Files/R/R-2.15.3/library/Rcpp/lib/x64/libRcpp.a: No such file or directory
> > ERROR: compilation failed for package 'mirt'
> > - removing 'C:/Program Files/R/R-2.15.3/library/mirt'
> > - restoring previous 'C:/Program Files/R/R-2.15.3/library/mirt'
> >   Error: Command failed (1)

The problem appears to be with the file names on my system, specifically the space in "C:/Program Files" (i.e., between "Program" and "Files".  That piece repeated is:

> g++.exe: error: C:/Program: No such file or directory
> g++.exe: error: Files/R/R-2.15.3/library/Rcpp/lib/x64/libRcpp.a: No such file or directory
> ERROR: compilation failed for package 'mirt'

Can you help?  

I'm using R version 2.15.3 (2013-03-01) on a laptop running Windows 7 x64 Image v2.  I installed Rtools30.exe yesterday (from http://cran.r-project.org/bin/windows/Rtools/).

Thanks -

Kevin Stanford
Cincinnati, Ohio  USA

**Comment by mukhendra** [comment]
Hi Phil,
I'm trying to install mirt package in my linux instance through using github link while trying to 
 I'm getting error. Even though all my dependencies like ( gcc,g++, gportran) installed successfully.

Steps followed : 
![image](https://user-images.githubusercontent.com/40772418/81814323-479de180-9546-11ea-9eeb-f3464d396b93.png)


Please find the screen shot below for your reference :
![image](https://user-images.githubusercontent.com/40772418/81814078-ea099500-9545-11ea-91f5-f18af96d19f6.png)

**Comment by philchalmers** [comment]
What is your compiler/system information? It looks like the reduction()
definition is not consistent in your implementation for some reason. Worst
case you can always disable the -fopenmp flag during installation to avoid
this preprocessor information.

Phil

**Comment by xxxiexuan** [comment]
Like above (mukhendra said), I have same error on install mirt in linux (CentOs 7)……

**Comment by philchalmers** [comment]
On Mac this preprocessor information is no doubt ignored since OpenMP is not supported in the most common compilers. What compilers are you using to install mirt? It's difficult to speculate on the issue without background information (e.g., mirt works fine on many different flavours of linux: https://cran.r-project.org/web/checks/check_results_mirt.html).

**Comment by xxxiexuan** [comment]
`R --version`
R version 3.6.0 (2019-04-26) -- "Planting of a Tree"
Copyright (C) 2019 The R Foundation for Statistical Computing
Platform: x86_64-redhat-linux-gnu (64-bit)

`git clone https://github.com/philchalmers/mirt`
`R CMD INSTALL mirt`
Estep.cpp: In function ‘void _Estep(std::vector<double>&, std::vector<double>&, const std::vector<double>&, const std::vector<double>&, const IntegerMatrix&, const NumericMatrix&, const bool&)’:
Estep.cpp:29:36: error: expected ‘+’, ‘*’, ‘-’, ‘&’, ‘^’, ‘|’, ‘&&’, ‘||’, ‘min’ or ‘max’ before ‘vec_double_plus’
 #pragma omp parallel for reduction(vec_double_plus : r1vec)
……

`library('devtools')`
`install_github('philchalmers/mirt')`
Estep.cpp: In function ‘void _Estep(std::vector<double>&, std::vector<double>&, const std::vector<double>&, const std::vector<double>&, const IntegerMatrix&, const NumericMatrix&, const bool&)’:
   Estep.cpp:29:36: error: expected ‘+’, ‘*’, ‘-’, ‘&’, ‘^’, ‘|’, ‘&&’, ‘||’, ‘min’ or ‘max’ before ‘vec_double_plus’
    #pragma omp parallel for reduction(vec_double_plus : r1vec)
……
Error: Failed to install 'mirt' from GitHub:
  System command 'R' failed, exit status: 1, stdout + stderr (last 10 lines):
E>                                     ^
E> Estep.cpp: In function ‘void _Estepbfactor(std::vector<double>&, std::vector<double>&, std::vector<double>&, std::vector<double>&, const NumericMatrix&, const NumericMatrix&, const std::vector<double>&, const std::vector<double>&, const IntegerMatrix&, const IntegerMatrix&, const bool&)’:
E> Estep.cpp:173:36: error: expected ‘+’, ‘*’, ‘-’, ‘&’, ‘^’, ‘|’, ‘&&’, ‘||’, ‘min’ or ‘max’ before ‘vec_double_plus’
E>  #pragma omp parallel for reduction(vec_double_plus : r1vec)
……

> What compilers are you using to install mirt?…… background information
And, i don't know what more to provide?

**Comment by philchalmers** [comment]
Are you using g++ with support for C++11 to compile mirt? Notice the following in my linux compiling information (copy-and-pasted):

```
> R CMD INSTALL mirt
* installing to library ‘/home/phil/R/x86_64-pc-linux-gnu-library/3.6’
* installing *source* package ‘mirt’ ...
** using staged installation
** libs
g++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG  -I"/home/phil/R/x86_64-pc-linux-gnu-library/3.6/Rcpp/include" -I"/home/phil/R/x86_64-pc-linux-gnu-library/3.6/RcppArmadillo/include"  -fopenmp -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-V28x5H/r-base-3.6.3=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c Estep.cpp -o Estep.o
g++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG  -I"/home/phil/R/x86_64-pc-linux-gnu-library/3.6/Rcpp/include" -I"/home/phil/R/x86_64-pc-linux-gnu-library/3.6/RcppArmadillo/include"  -fopenmp -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-V28x5H/r-base-3.6.3=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c Misc.cpp -o Misc.o
g++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG  -I"/home/phil/R/x86_64-pc-linux-gnu-library/3.6/Rcpp/include" -I"/home/phil/R/x86_64-pc-linux-gnu-library/3.6/RcppArmadillo/include"  -fopenmp -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-V28x5H/r-base-3.6.3=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c dpars.cpp -o dpars.o
g++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG  -I"/home/phil/R/x86_64-pc-linux-gnu-library/3.6/Rcpp/include" -I"/home/phil/R/x86_64-pc-linux-gnu-library/3.6/RcppArmadillo/include"  -fopenmp -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-V28x5H/r-base-3.6.3=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c ggum_derivs.cpp -o ggum_derivs.o
g++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG  -I"/home/phil/R/x86_64-pc-linux-gnu-library/3.6/Rcpp/include" -I"/home/phil/R/x86_64-pc-linux-gnu-library/3.6/RcppArmadillo/include"  -fopenmp -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-V28x5H/r-base-3.6.3=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c traceLinePts.cpp -o traceLinePts.o
g++ -std=gnu++11 -shared -L/usr/lib/R/lib -Wl,-Bsymbolic-functions -Wl,-z,relro -o mirt.so Estep.o Misc.o dpars.o ggum_derivs.o traceLinePts.o -llapack -lblas -lgfortran -lm -lquadmath -fopenmp -L/usr/lib/R/lib -lR
installing to /home/phil/R/x86_64-pc-linux-gnu-library/3.6/00LOCK-mirt/00new/mirt/libs
** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading
Creating a new generic function for ‘Deriv’ in package ‘mirt’
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
** checking absolute paths in shared objects and dynamic libraries
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (mirt)
```

**Comment by xxxiexuan** [comment]
>`R CMD INSTALL mirt`
* installing to library ‘/usr/lib64/R/library’
* installing *source* package ‘mirt’ ...
** using staged installation
** libs
g++ -m64 -std=gnu++11 -I"/usr/include/R" -DNDEBUG  -I"/usr/lib64/R/library/Rcpp/include" -I"/usr/lib64/R/library/RcppArmadillo/include" -I/usr/local/include -fopenmp -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic  -c Estep.cpp -o Estep.o
Estep.cpp:9:0: warning: ignoring #pragma omp declare [-Wunknown-pragmas]
 #pragma omp declare reduction(vec_double_plus : std::vector<double> : \
 ^
Estep.cpp: In function ‘void _Estep(std::vector<double>&, std::vector<double>&, const std::vector<double>&, const std::vector<double>&, const IntegerMatrix&, const NumericMatrix&, const bool&)’:
Estep.cpp:29:36: error: expected ‘+’, ‘*’, ‘-’, ‘&’, ‘^’, ‘|’, ‘&&’, ‘||’, ‘min’ or ‘max’ before ‘vec_double_plus’
 #pragma omp parallel for reduction(vec_double_plus : r1vec)

**Comment by philchalmers** [comment]
Strange, it looks like C++11 is being used. What g++ version are you running?

**Comment by xxxiexuan** [comment]
`gcc --version`
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39)

**Comment by philchalmers** [comment]
That's `gcc`, not `g++`. Nevertheless, it looks like you are using pretty old compilers (my `g++` is version  7.5.0 on Ubuntu OS, and that compiles fine). Try updated your compilers since `reduction` has likely changed across versions.

**Comment by xxxiexuan** [comment]
`g++ --version`
g++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39) ^-^

Let me try update gcc ……

**Comment by xxxiexuan** [comment]
After updated from 4.8.5 (g++ default version in CentOs 7) to 7.3.1
`g++ --version`
g++ (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)

Run in R console
`> install.packages('mirt')`
……
Making 'packages.html' ... done

`> library(mirt)`
`Loading required package: stats4`
`Loading required package: lattice`

Everything is ok !
Thanks.

**Comment by philchalmers** [comment]
Glad to hear it. @mukhendra try updating your compilers as well, and re-open this issue if the problem persists.

**Comment by mukhendra** [comment]
Hi Phil/xxxiexuan,

Thanks for the reply. may I know how to update g++ version from 4.5 to 7.3 version in Redhat 7.8 version. 
Please send me any reference links.

Regards,
Mukhendra

**Comment by mukhendra** [comment]
Hi Phil/Xxxiexuan,

Please find the below description steps, while installing gcc version

After updating gcc/g++ version from 4.8.5 to 9.3.0. Still I'm getting error while installing mirt package.
For reference gcc version:
![image](https://user-images.githubusercontent.com/40772418/82329489-06527980-99ff-11ea-921c-6901652be4ab.png)

Error 
![image](https://user-images.githubusercontent.com/40772418/82330098-030bbd80-9a00-11ea-81a3-c6e1e63da52d.png)

Regards,
Mukhendra

**Comment by xxxiexuan** [comment]
> Hi Phil/xxxiexuan,
> 
> Thanks for the reply. may I know how to update g++ version from 4.5 to 7.3 version in Redhat 7.8 version.
> Please send me any reference links.
> 
> Regards,
> Mukhendra

About g++……
`sudo yum install centos-release-scl`
`sudo yum install devtoolset-7-gcc*`
`scl enable devtoolset-7 bash`
`which gcc`
`gcc --version`

**Comment by christiandag** [comment]
> 
> 
> > Hi Phil/xxxiexuan,
> > Thanks for the reply. may I know how to update g++ version from 4.5 to 7.3 version in Redhat 7.8 version.
> > Please send me any reference links.
> > Regards,
> > Mukhendra
> 
> About g++…… `sudo yum install centos-release-scl` `sudo yum install devtoolset-7-gcc*` `scl enable devtoolset-7 bash` `which gcc` `gcc --version`
> 
> I write `scl enable devtoolset-7 bash` at /etc/profile.

After updating from 4.8.5 to 7.3.1, installation of mirt works fine, for centos 7.6 x64
